# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='settings',
            field=models.ManyToManyField(related_name='settings', to='services.Setting', verbose_name='Settings'),
        ),
    ]
