# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 04:09
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170731_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('template_type', models.IntegerField(choices=[(0, 'Django (Web)'), (1, 'Django Rest'), (2, 'iOS (Mobile)'), (4, 'S.P.A.'), (5, 'E-Commerce')], default=0, verbose_name='Template Type')),
                ('repo_url', models.TextField(verbose_name='Repo Url')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
            bases=(models.Model, core.models.ModelDiffMixin),
        ),
        migrations.AlterField(
            model_name='service',
            name='identifier',
            field=models.IntegerField(choices=[(0, 'Github'), (1, 'Bitbucket'), (2, 'Jira'), (3, 'Odoo')], default=0, max_length=50, verbose_name='Identifier'),
        ),
    ]
