# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170809_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='identifier',
            field=models.IntegerField(choices=[(0, 'Github'), (1, 'Bitbucket'), (2, 'Jira'), (3, 'Odoo')], default=0, verbose_name='Identifier'),
        ),
    ]
